# This is a basic workflow to help you get started with Actions

name: Intro

# Controls when the workflow will run
on:
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ secrets.CONTROLLER_REPO_OWNER }}
          repositories: ${{ secrets.CONTROLLER_REPO }}
          
      - name: Introduce Member
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ secrets.CONTROLLER_REPO_OWNER }}/${{ secrets.CONTROLLER_REPO }}
          event-type: intro
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "sender": "${{ github.actor }}",
                "owner": "${{ github.event.issue.user.login }}",
                "title": "${{ github.event.issue.title }}",
                "body": "${{ github.event.issue.body }}"
              }
            }
